# Generated by Django 4.1.3 on 2022-11-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50, verbose_name='plate_number')),
                ('vin_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='vin_code')),
                ('client', models.CharField(max_length=200, verbose_name='client')),
            ],
        ),
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Enter the car brand', max_length=100, verbose_name='brand')),
                ('car_model', models.CharField(help_text='Enter the car model', max_length=100, verbose_name='model')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=20, verbose_name='date')),
                ('total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='total')),
                ('status', models.CharField(choices=[('w', 'waiting for payment'), ('p', 'paid, car in warehouse'), ('d', 'delivered for client')], default='w', max_length=1, verbose_name='status')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_moto.car', verbose_name='car_id')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Order_row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_moto.order', verbose_name='order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_moto.service', verbose_name='service')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_moto.car_model', verbose_name='car_model'),
        ),
    ]
